# Generated by Django 4.2.10 on 2024-02-28 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ISISUsers', '0003_experiment_end_date_experiment_start_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facility',
            name='country',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='facility',
            name='name',
            field=models.CharField(help_text='Enter the name of the Facility you work at.', max_length=200),
        ),
        migrations.AlterField(
            model_name='facility',
            name='postcode',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='facility',
            name='street',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='facility',
            name='town',
            field=models.CharField(max_length=1000),
        ),
    ]
