# Generated by Django 4.2.16 on 2024-11-20 14:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ISISUsers', '0005_facilityuser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facilityuser',
            name='facility',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ISISUsers.facility'),
        ),
    ]
